### ISSUE TITLE
How to import the package?

### ISSUE THREAD

**Issue by Becomebright** [mjhydri/1D-StateSpace#1]

**Comment by mjhydri** [comment]
To facilitate the import functionality, the names of some modules are modified. So make sure that you reinstalled the package. Then you can import and use the package as the following example:

'''
from jump_reward_inference.joint_tracker import joint_inference
estimator = joint_inference(1, plot=True)
output = estimator.process("C:/datasets/testdata/123.mp3")
print(output)
'''
